### ISSUE TITLE
Roll and double after post-crawford still mandatory

### ISSUE THREAD

**Issue by DonZampano** [Watzmann/TGSClient#4]
1) After post-crawford rolling is still mandatory, no auto-roll is triggered.
2) At 4:2 at a 5 pointer the leading player can double

**Comment by Watzmann** [comment]
Yes - that is the exact behavior like on a life board.

I have several stages of digital help. In this case here:

1) No help. You roll or even double. Maybe your opponent tells you that it's a dead cube. Maybe you want to intimidate a newbie. Maybe you have just not understood the game.

2) One click help: you understand the game and you don't want to have to roll. You won't double anyway since it is a dead cube. You click the toggle "double" to OFF (the label 'double' is not good and will be changed soon, also the state of that toggle will be visible, then). So you click "double" OFF to signal that you don't want to double and then everything is fine.

3) No click help (almost): even stage 2 with one click per dead-cube-game is too much work for you. You will never ever turn a dead cube and you consider it too much work to click the "autodouble" button once. Then set the toggle "deadcube" to OFF. Then the server will assume "double" OFF with dead cubes.

I still allow turning dead cubes in general, because there are players that want to do that. Freedom of action is important for me.

PS: the toggle deadcube exists. But due to some bug it isn't functional, yet. I implemented it just for myself, because I am too lazy for stage 2.

**Comment by DonZampano** [comment]
Hm, is this behaviour conformal to tournament rules?
Maybe you can leave it as you have for private matches but not for "official" tournaments.

**Comment by Watzmann** [comment]
Tournaments will have a set of settings that are fixed. Whatever tournament directors tell me (or maybe even will be able to set themselves).
